### PR TITLE
Add ability to initialize controller with custom projectId

### PR DESCRIPTION
**Pull request by laurenzlong**
CLI Controller can now be initialized with a project ID, example:
var controller = new EmulatorController({projectId: 'your-firebase-project-id'});

### CODE REVIEW

**Comment by jmdobry** [comment]
Can you explain why this was necessary? I was under the impression that `new Controller({ projectId: 'project-id' })` already worked.

**Comment by jmdobry** [comment]
Blocking #92

**Comment by jmdobry** [comment]
I should further explain that the Emulator process itself does not need a projectId, it gets the projectId from the fully qualified function name in the requests, hence why I don't think this is necessary.

**Comment by laurenzlong** [comment]
Yeah you're right. I was getting an error about something else, and it wasn't getting surfaced properly, so I thought it was the controller initialization that wasn't working. Closing this.

**Pull request closed without merging**
