### PR TITLE
Update Node.js version warning message

### LINKED ISSUE #292: Unexpected Node.js v6.11.5 warning after functions update
### Version info

**firebase-functions:**
2.0.2

**firebase-tools:**
4.0.0

**firebase-admin:**
5.12.1

### Steps to reproduce
Upgrade firebase functions to version 2.0.2 to use the Node.js 8 runtime

### Were you able to successfully deploy your functions?
Yes

### Expected behavior
Work with no warnings.

### Actual behavior
Warning: You're using Node.js v8.11.3 but Google Cloud Functions only supports v6.11.5.

### PR DESCRIPTION
**Pull request by laurenzlong**
Fixes https://github.com/firebase/firebase-functions/issues/292

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by laurenzlong** [comment]
I've decided to not include the minor Node version in the message, since sometimes GCF auto-upgrades functions to a new Node version if the existing one has been found to have vulnerabilities.

**Comment by CodingDoug** [comment]
Could we add a link to the docs that discusses changing that targeted node runtime?  The message currently states that node 6 and node 8 are supported, but the dev is given no guidance on how to make a choice, or which is the default.

https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version

**Comment by laurenzlong** [comment]
Since this error message isn't just for Firebase, we would also need instructions for gcloud users. I actually wasn't able to find anything on how to configure runtime with gcloud, https://cloud.google.com/sdk/gcloud/reference/functions/deploy does not have any flags for runtime. Perhaps it is not yet updated. Jason, do you have any idea on where to find documentation on selecting runtime? And do you think it would be beneficial to to include links in this warning message?

**Review by jmdobry — APPROVED** [review]

**Comment by jmdobry** [comment]
@ace-n Do you know?

**Comment by laurenzlong** [comment]
Thanks for approving! I don't have authorization to merge the pull request, can you do it if you're happy with it? And perhaps we can do a follow up PR to link to reference pages if one also exists for gcloud?

**Comment by gligoran** [comment]
Should this be change as well: https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/master/bin/emulator#L25-L27?

**Comment by Shyam-Chen** [comment]
Need to modify the engine used. (#281)

**Comment by dungahk** [comment]
@gligoran I think that should have been updated, just like the README (https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/master/README.md#note)

**Comment by grant** [comment]
Note: This change has been published.

**Pull request merged**
